version: '3.9'

services:
  # Express Server
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@pg:5433/${PG_DATABASE}?:schema=${PG_SCHEMA}
      PORT: 4040
    depends_on:
      - pg
    restart: unless-stopped
    command: ['dumb-init', 'node', 'dist/index.js']

  # PostgreSQL Database
  pg:
    image: postgres:14.5-alpine
    container_name: pg
    ports:
      - '5433:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    env_file:
      - ./.env
    restart: always

volumes:
  pg-data:
